__author__ = 'andreacatalucci'

NUM_BEDROOMS = 3
MIN_PRICE_PER_WEEK = 440
MAX_PRICE_PER_WEEK = 500
MIN_PRICE_PER_MONTH = 1750
Max_PRICE_PER_MONTH = 2250
SEARCH_LOCATION = 'Oxford%20Circus%2C%20London'
MAX_DISTANCE_MILES = 3
RIGHTMOVE_POSTCODE = 'REGION^93980'
ZOOPLA_LOCATION = 'oxford-circus'
MAX_TRAVEL_TIME_SECONDS = 1800